Resolve #137 Relaxed HomeBrew requirement
Check against HomeBrew only if missing dependencies need to be installed

diff --git a/src/docker-osx-dev b/src/docker-osx-dev
--- a/src/docker-osx-dev
+++ b/src/docker-osx-dev
@@ -600,11 +600,6 @@ function check_prerequisites {
     log_error "This script should only be run on OS X"
     exit 1
   fi
-
-  if ! type brew > /dev/null 2>&1 ; then
-    log_error "This script requires HomeBrew, but it's not installed. Aborting."
-    exit 1
-  fi
 }
 
 #
@@ -627,16 +622,14 @@ function brew_install {
   local readonly command_name="$3"
   local readonly use_cask="$4"
 
-  local brew_command="brew"
-  if [[ "$use_cask" = true ]]; then
-    brew_command="brew cask"
-  fi
+  if ! type "$command_name" > /dev/null 2>&1 ; then
+    check_homebrew $readable_name
 
-  if eval "$brew_command list $package_name" > /dev/null 2>&1 ; then
-    log_warn "$readable_name is already installed by HomeBrew, skipping"
-  elif type "$command_name" > /dev/null 2>&1 ; then
-    log_warn "Found command $command_name, assuming $readable_name is already installed and skipping"
-  else
+    local brew_command="brew"
+    if [[ "$use_cask" = true ]]; then
+      brew_command="brew cask"
+    fi
+
     log_info "Installing $readable_name"
     eval "$brew_command install $package_name"
 
@@ -649,6 +642,20 @@ function brew_install {
       log_error "Failed to install dependency $readable_name. Check the log output above for reasons."
       exit 1
     fi
+  else
+    log_warn "Found command $command_name, assuming $readable_name is already installed and skipping"
+  fi
+}
+
+#
+# Checks if HomeBrew is installed.
+# Called only in case of a missing dependency.
+#
+function check_homebrew {
+  local readonly missing_package="$1"
+  if ! type brew > /dev/null 2>&1 ; then
+    log_error "HomeBrew is required to install $missing_package, but it's not installed. Aborting."
+    exit 1
   fi
 }
 
