Add Brew update method to encapsulate failures

diff --git a/src/docker-osx-dev b/src/docker-osx-dev
--- a/src/docker-osx-dev
+++ b/src/docker-osx-dev
@@ -603,6 +603,20 @@ function check_prerequisites {
 }
 
 #
+# Update Brew formulae and HomeBrew
+#
+# Non-breaking. Falls through with warning if fails.
+#
+function brew_update {
+  log_info "Updating HomeBrew"
+  if ! type brew > /dev/null 2>&1 ; then
+    log_warn "HomeBrew not found, attempting to continue without"
+  else
+    brew update
+  fi
+}
+
+#
 # Usage: brew_install PACKAGE_NAME READABLE_NAME COMMAND_NAME USE_CASK
 #
 # Checks if PACKAGE_NAME is already installed by using brew as well as by
@@ -635,16 +649,16 @@ function brew_install {
     else
       log_info "Installing $readable_name"
       eval "$brew_command install $package_name"
-    fi
 
-    # It seems that brew install can fail to install a dependency, but exit
-    # without an error code, so the set -e flag does not help us. Example:
-    # https://github.com/brikis98/docker-osx-dev/issues/124
-    # Therefore, explicitly check that the dependency was installed before
-    # proceeding.
-    if ! type "$command_name" > /dev/null 2>&1; then
-      log_error "Failed to install dependency $readable_name. Check the log output above for reasons."
-      exit 1
+      # It seems that brew install can fail to install a dependency, but exit
+      # without an error code, so the set -e flag does not help us. Example:
+      # https://github.com/brikis98/docker-osx-dev/issues/124
+      # Therefore, explicitly check that the dependency was installed before
+      # proceeding.
+      if ! type "$command_name" > /dev/null 2>&1; then
+        log_error "Failed to install dependency $readable_name. Check the log output above for reasons."
+        exit 1
+      fi
     fi
   else
     log_warn "Found command $command_name, assuming $readable_name is already installed and skipping"
@@ -667,8 +681,7 @@ function check_homebrew {
 # Installs all the dependencies for docker-osx-dev.
 #
 function install_dependencies {
-  log_info "Updating HomeBrew"
-  brew update
+  brew_update
 
   brew_install "caskroom/cask/brew-cask" "Cask" "brew cask" false
   brew_install "boot2docker" "Boot2Docker" "boot2docker" false
