Simplify rsync install
For some reason, tce-load exits with an error even after a successful
install of rsync. Therefore, manually recheck if the install worked,
and if it didn’t, fall back to installing via the pre-built rsync
binary in the GitHub repo.

diff --git a/src/docker-osx-dev b/src/docker-osx-dev
--- a/src/docker-osx-dev
+++ b/src/docker-osx-dev
@@ -39,7 +39,6 @@ readonly DEFAULT_COMMAND="$SYNC_COMMAND"
 readonly BIN_DIR="/usr/local/bin"
 
 # docker host constants
-
 readonly BOOT2DOCKER_USER="docker"
 
 # docker-compose constants
@@ -450,22 +449,16 @@ function init_docker_host {
 function install_rsync_on_docker_host {
   log_info "Installing rsync in the Docker Host image"
 
-  if $DOCKER_HOST_SSH_COMMAND "if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi" ; then
-    log_info "Successfully installed rsync in the Docker Host Image"
-  else
-    log_info "Failed to install rsync from existing mirror"
-    log_info "Backing up existing mirror and changing mirror to http://distro.iblibio.org/"
-    $DOCKER_HOST_SSH_COMMAND "cat /opt/tcemirror > /tmp/tcemirror.bak"
-    $DOCKER_HOST_SSH_COMMAND "echo 'http://distro.ibiblio.org/' > /opt/tcemirror"
-    if $DOCKER_HOST_SSH_COMMAND "tce-load -wi rsync" ; then
-      log_info "Successfully installed rsync from http://distro.ibiblio.org/"
-    else
-      log_info "Failed to install rsync from http://distro.ibiblio.org/"
-      log_info "Installing rsync from GitHub"
+  if ! $DOCKER_HOST_SSH_COMMAND "if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi"; then
+
+    # For some reason, the tce-load command often exits with an error code, even
+    # if rsync installed successfully. Therefore, re-run just the type command
+    # to see if it actually worked
+
+    if ! $DOCKER_HOST_SSH_COMMAND "type rsync > /dev/null 2>&1" ; then
+      log_info "Failed to install rsync using tce-load, falling back to install rsync from pre-built binary in docker-osx-dev GitHub repo"
       $DOCKER_HOST_SSH_COMMAND "sudo wget -P $BIN_DIR $RSYNC_BINARY_URL && sudo chmod +x $BIN_DIR/rsync"
     fi
-    log_info "Restoring original tce-load mirror"
-    $DOCKER_HOST_SSH_COMMAND "cat /tmp/tcemirror.bak > opt/tcemirror"
   fi
 }
 
